
import { MenuItem } from './types';

export const menuItems: MenuItem[] = [
  {
    id: "sp-1",
    name: "Chef's Seasonal Special",
    nameZh: "主廚季節限定",
    description: "Our latest creation featuring exclusive seasonal ingredients imported directly from Napoli.",
    descriptionZh: "主廚最新創作，選用由拿坡里直接進口的獨家季節性食材。",
    price: "HK$ 298",
    category: "Contemporary Pizza",
    categoryZh: "當代薄餅",
    image: "https://storage.googleapis.com/xps-assets/gotti's%20assets%20/BRAND%20ASSETS/vincenzo%20h%26k/exclusive-chiligrab.jpg",
    popular: true,
    dietary: [],
    chefNote: "Every season brings new gifts from the earth. This is my homage to the current harvest.",
    chefNoteZh: "每個季節都帶來大地的新禮物。這是對當前收成的致敬。"
  },
  {
    id: "st-1",
    name: "Frittatina Napoletana",
    nameZh: "拿坡里炸意粉球",
    description: "Bucatini pasta, bechamel, pepper, minced meat, grana padano, Provola, basil.",
    descriptionZh: "長通粉、白汁、胡椒、肉碎、帕馬森芝士、煙燻芝士及羅勒。",
    price: "HK$ 118",
    category: "Starters",
    categoryZh: "精選前菜",
    image: "https://storage.googleapis.com/xps-assets/gotti's%20assets%20/BRAND%20ASSETS/vincenzo%20h%26k/detto-fatto-pizza.png",
    dietary: [],
    chefNote: "A classic Neapolitan street food. The crunch outside must protect the creamy treasure inside.",
    chefNoteZh: "拿坡里經典街頭小食。香脆的外殼包裹著內裡豐富的忌廉內餡。"
  },
  {
    id: "st-2",
    name: "Parmigiana Di Melanzane",
    nameZh: "焗芝士千層茄子",
    description: "Tomato, fried aubergines, grana padano cheese, basil. Alla Nonno Enzo style.",
    descriptionZh: "番茄、炸茄子、帕馬森芝士及羅勒。遵循 Enzo 祖父的傳統食譜。",
    price: "HK$ 148",
    category: "Starters",
    categoryZh: "精選前菜",
    image: "https://storage.googleapis.com/xps-assets/gotti's%20assets%20/BRAND%20ASSETS/vincenzo%20h%26k/gwanciale-di-manzo.jpg",
    dietary: ["Vegetarian"],
    chefNote: "My grandfather Enzo's recipe. The key is in how thinly you slice the aubergines.",
    chefNoteZh: "來自祖父 Enzo 的家傳食譜。關鍵在於將茄子切得極薄。"
  },
  {
    id: "cp-1",
    name: "Provola E Pepe",
    nameZh: "煙燻芝士黑椒薄餅",
    description: "World Champion 2019. Smoked provola, hand-crushed tomatoes, pepper mix, roasted cherry tomatoes.",
    descriptionZh: "2019 世界冠軍作品。煙燻芝士、手壓番茄、特調胡椒及烤小番茄。",
    price: "HK$ 228",
    category: "Contemporary Pizza",
    categoryZh: "當代薄餅",
    image: "https://storage.googleapis.com/xps-assets/gotti's%20assets%20/BRAND%20ASSETS/vincenzo%20h%26k/provola-e-pepe.png",
    popular: true,
    dietary: ["Vegetarian"],
    chefNote: "The World Champion pizza. The balance of smoked cheese and fresh pepper is what won the judges' hearts.",
    chefNoteZh: "2019年世界冠軍作品。煙燻芝士與新鮮胡椒的平衡完美征服了評委。"
  },
  {
    id: "cp-3",
    name: "Centro Calabria",
    nameZh: "卡拉布里亞之星",
    description: "San Marzano sauce, smoked provola, calabrian nduja, neapolitan sausage, evoo & basil.",
    descriptionZh: "San Marzano 番茄醬、煙燻芝士、卡拉布里亞辣肉醬、拿坡里肉腸、橄欖油及羅勒。",
    price: "HK$ 248",
    category: "Contemporary Pizza",
    categoryZh: "當代薄餅",
    image: "https://storage.googleapis.com/xps-assets/gotti's%20assets%20/BRAND%20ASSETS/vincenzo%20h%26k/pizza.png",
    popular: true,
    dietary: ["Spicy"],
    chefNote: "Spicy, bold, and unapologetic. The 'Nduja melts into the sauce creating liquid gold.",
    chefNoteZh: "香辣、大膽。卡拉布里亞辣肉醬融化在醬汁中，如同液態黃金。"
  },
  {
    id: "tp-2",
    name: "Margherita",
    nameZh: "瑪格麗特薄餅",
    description: "Hand-crushed tomato, fior di latte from the mountains, evoo & basil.",
    descriptionZh: "手壓番茄、高山莫札瑞拉芝士、初榨橄欖油及羅勒。",
    price: "HK$ 208",
    category: "Traditional Pizza",
    categoryZh: "傳統薄餅",
    image: "https://storage.googleapis.com/xps-assets/gotti's%20assets%20/BRAND%20ASSETS/vincenzo%20h%26k/auth-nepolitan.jpg",
    dietary: ["Vegetarian"],
    chefNote: "The queen of pizzas. San Marzano tomatoes and Fior di Latte are the flag of Italy.",
    chefNoteZh: "薄餅之後。San Marzano 番茄和 Fior di Latte 芝士象徵著意大利的色彩。"
  },
  {
    id: "pst-3",
    name: "Carbonara",
    nameZh: "傳統卡邦尼意粉",
    description: "Home-made fettuccine, slow cooked iberico pork jowl, egg yolk, parmigiano.",
    descriptionZh: "自家製闊麵、慢煮伊比利亞豬頰肉、蛋黃及帕馬森芝士。",
    price: "HK$ 228",
    category: "Pasta",
    categoryZh: "手製意粉",
    image: "https://storage.googleapis.com/xps-assets/gotti's%20assets%20/BRAND%20ASSETS/vincenzo%20h%26k/pasta.png",
    dietary: [],
    chefNote: "No cream! Just egg yolk, pecorino, and pepper emulsion. Roman tradition respected.",
    chefNoteZh: "絕不加忌廉！純粹以蛋黃、羊奶芝士和胡椒乳化而成。向羅馬傳統致敬。"
  },
  {
    id: "dst-1",
    name: "Tiramisu All'Amaretto",
    nameZh: "杏仁酒提拉米蘇",
    description: "Mascarpone lombardo, savoiardi biscuit, crushed pistachio, amaretto, physalis.",
    descriptionZh: "倫巴第馬斯卡彭芝士、手指餅乾、開心果碎、杏仁酒及燈籠果。",
    price: "HK$ 138",
    category: "Dessert",
    categoryZh: "甜品",
    image: "https://storage.googleapis.com/xps-assets/gotti's%20assets%20/BRAND%20ASSETS/vincenzo%20h%26k/egg-yolk.png",
    dietary: ["Contains Nuts"],
    chefNote: "The amaretto adds a nutty warmth to the coffee soak.",
    chefNoteZh: "杏仁酒為咖啡浸透的手指餅乾增添了一抹溫緩的果仁香氣。"
  }
];
